services:
  - type: web
    name: ecommerce-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "run:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
