openapi: 3.0.0
info:
  title: E-commerce API
  version: 1.0.0
paths:
  /auth/register:
    post: { summary: Register a new user }
  /auth/login:
    post: { summary: Login and get tokens }
  /auth/refresh:
    post: { summary: Refresh JWT token }
  /auth/me:
    get: { summary: Get current user info }

  /users/me:
    get: { summary: Get account }
    put: { summary: Update account }
    delete: { summary: Delete account }

  /products:
    get: { summary: Get all products }
    post: { summary: Create new product }
  /products/{id}:
    get:
      {
        summary: Get product by ID,
        parameters: [{ in: path, name: id, schema: { type: integer } }],
      }
    put: { summary: Update product by ID }
    delete: { summary: Delete product by ID }

  /carts:
    get: { summary: View current cart }
    post: { summary: Add item to cart }
  /carts/{item_id}:
    delete: { summary: Remove item from cart }

  /orders:
    get: { summary: List user orders }
    post: { summary: Checkout }
  /orders/{id}:
    get: { summary: Get order by ID }
