"""add description and brand to Product

Revision ID: 6820ce825333
Revises: b4cf38f001a2
Create Date: 2025-09-04 11:27:12.942512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6820ce825333'
down_revision = 'b4cf38f001a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('brand')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
